import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "leaflet/dist/leaflet.css";
import "./globals.css";
import Navbar from "./components/Navbar";


const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.className}>
      <body className="pt-[68px]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
